version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/src
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: go run main.go

  db:
    image: mysql:8.0
    volumes:
      - data-volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${DB_TZ}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_TCP_PORT: 3306
    command: --character-set-server=utf8mb4 --collation-server=${DB_COLLATION}

volumes:
  data-volume:
